In [1]:
from IPython.display import Image

In [4]:
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch13/figures/13_01.png', width=400)

파이토치로 구현

In [5]:
import torch

In [6]:
def compute_z(a, b, c):
  r1 = torch.sub(a,b)
  r2 = torch.mul(r1,2)
  z = torch.add(r2,c)
  return z

In [7]:
a,b,c = torch.tensor(1),torch.tensor(2), torch.tensor(3)
print("스칼라 입력 : ",  compute_z(a,b,c) )
a,b,c = torch.tensor([1]),torch.tensor([2]), torch.tensor([3])
print("랭크 1 입력 : ",  compute_z(a,b,c) )
a,b,c = torch.tensor([[1]]),torch.tensor([[2]]), torch.tensor([[3]])
print("랭크 2 입력 : ",  compute_z(a,b,c) )

스칼라 입력 :  tensor(1)
랭크 1 입력 :  tensor([1])
랭크 2 입력 :  tensor([[1]])


In [8]:
a = torch.tensor(3.14, requires_grad=True)
b = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(a)
print(b)

tensor(3.1400, requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [11]:
a.requires_grad

True

In [12]:
w = torch.tensor([1.0, 2.0, 3.0])
w.requires_grad

False

In [13]:
w.requires_grad_()  # 그레이드 적용
w.requires_grad

True

In [15]:
import torch.nn as nn
torch.manual_seed(1)
w = torch.empty(2,3)
print(w)
nn.init.xavier_normal_(w)  # xavier초기화를 적용해서 w의 값을 초기화  , xavier초기화는 신경망의 가중치를 적절하게 초기화해서 그레이디언트의 전파를 개선
print(w)

tensor([[-3.1350e+29,  4.5891e-41, -1.3772e-14],
        [ 3.0890e-41,  4.4842e-44,  0.0000e+00]])
tensor([[ 0.4183,  0.1688,  0.0390],
        [ 0.3930, -0.2858, -0.1051]])


In [16]:
class MyModule(nn.Module):
  def __init__(self):
    self.w1 = torch.empty(2,3, requires_grad=True)
    nn.init.xavier_normal_(self.w1)
    self.w2 = torch.empty(1,2, requires_grad=True)
    nn.init.xavier_normal_(self.w2)

자동 미분으로 그레이디언트 계산

In [20]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.5, requires_grad=True)

x = torch.tensor([1.4])
y = torch.tensor([2.1])

z = torch.add(torch.mul(w,x), b)

loss = (y- z).pow(2).sum()
loss.backward()

print("dL/dW :",w.grad)
print("dL/db :",b.grad)

dL/dW : tensor(-0.5600)
dL/db : tensor(-0.4000)


In [22]:
2*x*((w*x+b) - y)

tensor([-0.5600], grad_fn=<MulBackward0>)